sudo: required
services:
  - docker

before_install:
  - docker build -t fschettini/docker-react -f Dockerfile.dev .      

script:
  - docker run fschettini/docker-react npm run test -- --coverage 

deploy: 
  provide: elasticbeanstalk
  region:  "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-235727411841"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"